repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # pre-commit version
    hooks:
    - id: check-toml  # checks toml files for parseable syntax.
    - id: name-tests-test # verifies that test files are named correctly.
      args: [--pytest-test-first]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4 # ruff version
    hooks:
      - id: ruff  # run the linter
      - id: ruff-format # run the formatter
